# Generated by Django 3.0.6 on 2020-05-13 07:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello', '0007_auto_20200513_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friendRequests',
        ),
        migrations.AddField(
            model_name='profile',
            name='friendRequests',
            field=models.ManyToManyField(null=True, related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(null=True, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
