# Generated by Django 3.0.6 on 2020-05-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_auto_20200518_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanbase',
            name='about',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
