# Generated by Django 3.0.6 on 2020-05-30 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello', '0011_auto_20200529_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('about', models.CharField(blank=True, max_length=2000)),
                ('careBuddies', models.ManyToManyField(blank=True, related_name='fans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='FanBase',
        ),
        migrations.AddField(
            model_name='plant',
            name='posts',
            field=models.ManyToManyField(related_name='posts', to='hello.Post'),
        ),
    ]
