# Generated by Django 3.0.6 on 2020-05-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0013_profile_plants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='plant',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='posts', to='hello.Post'),
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='hello.Comment'),
        ),
    ]
